# # [Shrinking the CHSH SDP with Symmetry](@id chsh-symmetry)
#
# The CHSH inequality is the standard Bell-inequality warm-up:
#
# ```math
# S = A_1 B_1 + A_1 B_2 + A_2 B_1 - A_2 B_2,
# ```
#
# with `A_i^2 = B_j^2 = I` and `[A_i, B_j] = 0`. The quantum maximum is
# Tsirelson's bound `2\sqrt{2}`.
#
# The [Bell inequalities](@ref bell-inequalities) page already certifies that
# bound with a dense moment relaxation. Here we take the next step: **use the
# symmetry of the CHSH operator to shrink the SDP** that the solver actually
# sees, while still recovering the same `2\sqrt{2}`.
#
# Concretely, this page shows how to:
#
# 1. solve a dense CHSH moment relaxation as a baseline,
# 2. write down the three signed-permutation generators that leave the CHSH
#    objective invariant,
# 3. wrap them in a [`SymmetrySpec`](@ref) and re-solve via
#    [`cs_nctssos`](@ref) using the `symmetry` keyword,
# 4. read off the resulting [`SymmetryReport`](@ref) — the dense `5\times 5`
#    moment matrix splits into three independent `1\times 1` PSD blocks, and
#    the eleven distinct moments collapse to one nontrivial invariant moment.
#
# **Prerequisites**: familiarity with the [Bell inequalities](@ref bell-inequalities)
# example. For the architectural picture (what stays local, what
# `SymbolicWedderburn` does, what is and isn't supported), see the manual page
# [Symmetry-Adapted Basis](@ref symmetry-adapted-basis).

using NCTSSoS, MosekTools

const MOI = NCTSSoS.MOI
const SILENT_MOSEK = MOI.OptimizerWithAttributes(
    Mosek.Optimizer,
    MOI.Silent() => true,
)
nothing #hide

# ## Step 1 — Build the CHSH problem
#
# We use unipotent variables, so `A_i^2 = I`, `B_j^2 = I`, and the bipartite
# commutation relations are encoded directly in the algebra. As usual,
# [`cs_nctssos`](@ref) minimizes, so to maximize `S` we minimize `-S`.

registry, (A, B) = create_unipotent_variables([("A", 1:2), ("B", 1:2)]);

S = 1.0 * A[1] * B[1] +
    1.0 * A[1] * B[2] +
    1.0 * A[2] * B[1] -
    1.0 * A[2] * B[2]

pop = polyopt(-S, registry);

# We will also fix an explicit half-basis so that the dense and the symmetric
# runs use exactly the same monomials and we can compare like with like:

Q = [one(A[1]), A[1], A[2], B[1], B[2]];
length(Q)

# ## Step 2 — Dense baseline: one `5\times 5` PSD block
#
# Without any sparsity or symmetry reduction, the order-1 CHSH relaxation
# builds a single moment matrix indexed by `Q`.

dense_config = SolverConfig(
    optimizer    = SILENT_MOSEK,
    moment_basis = Q,
    cs_algo      = NoElimination(),
    ts_algo      = NoElimination(),
)

dense_result = cs_nctssos(pop, dense_config);

# The objective recovers Tsirelson's bound:

dense_bound = -dense_result.objective

# Sanity check against the theoretical value:

abs(dense_bound - 2 * sqrt(2))

# The PSD block sizes confirm the dense layout — one block of side 5:

dense_result.moment_matrix_sizes

# and the relaxation distinguishes 11 moment variables:

dense_result.n_unique_moment_matrix_elements

# Note that the symmetry field is empty for a dense run:

dense_result.symmetry === nothing

# ## Step 3 — The three signed-permutation generators
#
# CHSH has a 16-element symmetry group. It is generated by three signed
# permutations of the four operators, each of which leaves
# `S = A_1 B_1 + A_1 B_2 + A_2 B_1 - A_2 B_2` invariant.
#
# A [`SignedPermutation`](@ref) is a bijection on registry indices, with an
# extra `\pm 1` sign per index. The constructor takes pairs
# `src => dst` (sign defaults to `+1`) or `src => (sign, dst)`. Indices not
# listed are fixed.
#
# The "raw" registry index of an operator is its underlying word index, e.g.
# `A[1].word[1]`.

# **Alice swap.** Swap `A_1 \leftrightarrow A_2` together with `B_2 \to -B_2`.
# Effect on the four CHSH terms:
# `A_1 B_1 \leftrightarrow A_2 B_1`,
# `A_1 B_2 \to -A_2 B_2`, and
# `-A_2 B_2 \to A_1 B_2`. Sum unchanged.

alice_swap = SignedPermutation(
    A[1].word[1] => A[2].word[1],
    A[2].word[1] => A[1].word[1],
    B[2].word[1] => (-1, B[2].word[1]),
)

# **Bob swap.** `A_2 \to -A_2` together with `B_1 \leftrightarrow B_2`.

bob_swap = SignedPermutation(
    A[2].word[1] => (-1, A[2].word[1]),
    B[1].word[1] => B[2].word[1],
    B[2].word[1] => B[1].word[1],
)

# **Party swap.** Exchange Alice and Bob: `A_i \leftrightarrow B_i`.

party_swap = SignedPermutation(
    A[1].word[1] => B[1].word[1],
    A[2].word[1] => B[2].word[1],
    B[1].word[1] => A[1].word[1],
    B[2].word[1] => A[2].word[1],
)

# A [`SymmetrySpec`](@ref) wraps the generators. By default, NCTSSoS will
# enumerate the full group locally, then *check* that the objective and every
# constraint really are invariant under it. If you trust the spec and want to
# skip the check, pass `check_invariance = false`.

spec = SymmetrySpec(alice_swap, bob_swap, party_swap)

# ## Step 4 — Solve with symmetry reduction
#
# The only change to the configuration is the `symmetry` keyword. The MVP
# requires a single dense clique with no term sparsity, which we already use:

sym_config = SolverConfig(
    optimizer    = SILENT_MOSEK,
    moment_basis = Q,
    cs_algo      = NoElimination(),
    ts_algo      = NoElimination(),
    symmetry     = spec,
)

sym_result = cs_nctssos(pop, sym_config);

# The objective still recovers Tsirelson's bound:

sym_bound = -sym_result.objective

# matched against the theoretical value:

abs(sym_bound - 2 * sqrt(2))

# and matched against the dense baseline:

abs(sym_bound - dense_bound)

# ## Step 5 — Read the [`SymmetryReport`](@ref)
#
# The `symmetry` field of the result is no longer `nothing`; it is a small
# struct summarizing what the symmetry path did.

report = sym_result.symmetry

# The full enumerated symmetry group has 16 elements:

report.group_order

# The original half-basis had 5 monomials; this matches what the dense run
# used:

(report.basis_half_size, report.basis_full_size)

# After orbit reduction, only **one** nontrivial invariant moment remains
# (in addition to the identity moment, which is always 1):

report.invariant_moment_count

# And — the headline change — the single dense PSD block of side 5 has been
# replaced by **three independent `1\times 1` PSD blocks**, one per isotypic
# component of the symmetry-adapted decomposition:

report.psd_block_sizes

# The result type itself prints this summary alongside the rest of the
# optimization output. Notice the split in reporting: `moment_matrix_sizes`
# keeps its pre-symmetry meaning (`[5]` here), while the actual reduced solver
# PSD blocks are printed separately from `report.psd_block_sizes`.

sym_result

# ## Step 6 — What changed and what did not
#
# Two observations are worth making explicit, because they capture the
# architectural decision behind this feature.
#
# **What changed (inside the SDP):**
#
# - One `5\times 5` PSD constraint became three independent `1\times 1` PSD
#   constraints.
# - Eleven distinct moment variables collapsed into one nontrivial invariant
#   moment plus the identity.
#
# **What did *not* change (the user-facing surface):**
#
# - The objective is still expressed in ordinary monomial coordinates.
# - The result is still a [`PolyOptResult`](@ref NCTSSoS.PolyOptResult) over
#   an ordinary [`MomentProblem`](@ref NCTSSoS.MomentProblem); the JuMP model,
#   the dualization path, and any downstream reconstruction tooling all see
#   plain monomial moments, not isotypic-component coordinates.
# - The objective value is unchanged (up to solver tolerance): the symmetry
#   reduction is *exact*, not an additional relaxation.
#
# This is the central trade-off: NCTSSoS uses the symmetry-adapted basis only
# **internally**, to decide how to slice one PSD block into several smaller
# ones, and emits the result back in monomial coordinates. The downside is
# that the current MVP only handles cases where every isotypic block is a
# `1\times 1` scalar (multiplicity-free, scalar blocks); the upside is that
# nothing else in the package — registries, polynomials, sparsity, GNS
# reconstruction — has to change.
#
# See [Symmetry-Adapted Basis](@ref symmetry-adapted-basis) for the full
# picture, including:
#
# - the supported MVP scope (dense, single clique, ordinary `PolyOpt` over
#   `MonoidAlgebra`, real signed permutations, multiplicity-free / scalar
#   blocks only),
# - the fail-fast behavior on unsupported cases (term sparsity, multiple
#   cliques, non-invariant objectives, basis closure failures, multiplicity
#   `> 1`, non-scalar blocks, state/trace problems, [`cs_nctssos_higher`](@ref),
#   and monomap-based GNS reconstruction from symmetry-reduced solves, which
#   still needs dense unreduced moments), and
# - the boundary between what NCTSSoS does locally and what
#   [`SymbolicWedderburn`](https://github.com/kalmarek/SymbolicWedderburn.jl)
#   computes for it.
#
# ## Summary
#
# | run | PSD block sizes | distinct moment variables | objective |
# |:----|:----------------|:--------------------------|:----------|
# | dense                    | `[5]`       | 11 | `-2\sqrt{2}` |
# | dense + symmetry (CHSH) | `[1, 1, 1]` | 1 (plus identity) | `-2\sqrt{2}` |
#
# Same answer, much smaller SDP — and the rest of the package is unchanged.
